# Generated by Django 4.1.5 on 2023-02-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_price',
        ),
    ]
